In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# unzip datset file

#!unzip /content/drive/MyDrive/December_projects/cyberbully/1L/cb_multi_labeled_balanced_D2.csv.zip -d /content/drive/MyDrive/December_projects/cyberbully/1L

Archive:  /content/drive/MyDrive/December_projects/cyberbully/1L/cb_multi_labeled_balanced_D2.csv.zip
  inflating: /content/drive/MyDrive/December_projects/cyberbully/1L/cb_multi_labeled_balanced.csv

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/December_projects/cyberbully/1L/cb_multi_labeled_balanced.csv')

df.head()

                                                text              label
0  @ZubearSays Any real nigga isn't letting this ...     ethnicity/race
1  @MoradoSkittle @prolifejewess @DAConsult @Kell...  not_cyberbullying
2        the only thing i wish, i wish a nigga would     ethnicity/race
3  You saudias are not friends of Muslim idiots c...           religion
4  @JaydenT2399 @TractorLaw @holmes_gael @erconge...           religion

In [3]:
df.shape

(99990, 2)

In [4]:
df.columns

Index(['text', 'label'], dtype='object')

In [5]:
df['label'].value_counts()

label
not_cyberbullying    50000
ethnicity/race       17000
gender/sexual        17000
religion             15990
Name: count, dtype: int64

In [6]:
# average word counts

# Calculate the average word count per tweet
df['word_count'] = df['text'].apply(lambda x: len(str(x).split()))
average_word_count = df['word_count'].mean()

print(f"The average word count is: {average_word_count}")

The average word count is: 21.330953095309532

In [7]:
# max word count
max_word_count = df['word_count'].max()
print(f"The maximum word count is: {max_word_count}")

The maximum word count is: 96

In [8]:
df['word_count'].describe()

count    99990.000000
mean        21.330953
std         13.461627
min          1.000000
25%         11.000000
50%         17.000000
75%         29.000000
max         96.000000
Name: word_count, dtype: float64

In [9]:
# undersampling all class to particular value

from sklearn.utils import resample

# Determine the minimum number of samples per class
min_samples = 15000

# Create an empty list to store the downsampled dataframes
downsampled_dfs = []

# Iterate through each class
for class_label in df['label'].unique():
    # Select the rows belonging to the current class
    class_df = df[df['label'] == class_label]

    # Downsample the current class to the minimum number of samples
    downsampled_class_df = resample(class_df, replace=False, n_samples=min_samples, random_state=42)

    # Append the downsampled dataframe to the list
    downsampled_dfs.append(downsampled_class_df)

# Concatenate all downsampled dataframes into a single dataframe
downsampled_df = pd.concat(downsampled_dfs)

print(downsampled_df['label'].value_counts())

label
ethnicity/race       15000
not_cyberbullying    15000
religion             15000
gender/sexual        15000
Name: count, dtype: int64

In [10]:
df_filtered = downsampled_df.copy()

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_filtered['label'] = le.fit_transform(df_filtered['label'])

# Create the dictionary mapping original labels to encoded labels
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

# Print the dictionary
label_mapping

{'ethnicity/race': 0,
 'gender/sexual': 1,
 'not_cyberbullying': 2,
 'religion': 3}

In [12]:
# save label_mapping as pickle

import pickle

# Save the label_mapping dictionary as a pickle file
with open('/content/drive/MyDrive/December_projects/cyberbully/label_mapping.pkl', 'wb') as f:
    pickle.dump(label_mapping, f)

In [14]:
df_filtered = df_filtered.drop(columns=['word_count'])
df_filtered.head()

                                                    text  label
64918  @Seveerity I guess only things she got is that...      0
31178  @Stravon_ @Christcucks2 You said the nigger wo...      0
60922  @TheVillageWareh @matinyarare @glen_mogau This...      0
13693             @KBthabuddhist Nigga really singin man      0
37864  @ImmuneHack @ScottAdamsSays I would take out t...      0

In [15]:
# save dataframe as csv
df_filtered.to_csv('/content/drive/MyDrive/December_projects/cyberbully/processed_1L_data.csv', index=False)